#!/usr/bin/env bash
# Configure domain zone so that the subdomain www
# points to load-balancer IP (lb-01)
# domain=$1
# subdomain=$2
configuration () {
    command_query=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $command_query" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" -eq 1 ]
then
    configuration "$1" "www"
    configuration "$1" "lb-01"
    configuration "$1" "web-01"
    configuration "$1" "web-02"
elif [ "$#" -eq 2 ]
then
    configuration "$1" "$2"
fi
